### ISSUE TITLE
apt: please support multiple packages

### ISSUE THREAD

**Issue by stapelberg** [larswirzenius/vmdb2#16]
Currently, for each package, a separate apt invocation is necessary. In the interest of speed, I’d like to install all the packages I need at once.

**Comment by llimeht** [comment]
I've got patches ready to go for this, but it needs a bug in jinja expansion #13 to be sorted out first.

**Comment by stapelberg** [comment]
@llimeht I think with https://github.com/larswirzenius/vmdb2/commit/ad3d77f64da20c3d8158346ee97780aeb12cc1ab, your patches can now be submitted :)

**Comment by larswirzenius** [comment]
I've implemented this now.

**Comment by stapelberg** [comment]
(with commit https://github.com/larswirzenius/vmdb2/commit/3d4f5713bba3bd453b9815cbf4317d12b1448534, for the record)
