### ISSUE TITLE
qemu-debootstrap: please add the components flag

### ISSUE THREAD

**Issue by stapelberg** [larswirzenius/vmdb2#17]
I’m using this patch for now, but I’m not sure whether you want to allow a list instead of a comma-separated string:

```diff
--- i/vmdb/plugins/qemudebootstrap_plugin.py
+++ w/vmdb/plugins/qemudebootstrap_plugin.py
@@ -39,11 +39,12 @@ class QemuDebootstrapStepRunner(vmdb.StepRunnerInterface):
         target = state.mounts[tag]
         mirror = step['mirror']
         variant = step.get('variant', '-')
+        components = step.get('components', 'main')
         arch = step['arch']
         if not (suite and tag and target and mirror and arch):
             raise Exception('missing arg for qemu-debootstrap step')
         vmdb.progress(
             'Qemu-debootstrap {} {} {} {}'.format(suite, target, mirror, arch))
         vmdb.runcmd(
-            ['qemu-debootstrap', '--arch', arch, '--variant', variant, suite,
-             target, mirror])
+            ['qemu-debootstrap', '--arch', arch, '--components', components,
+             '--variant', variant, suite, target, mirror])
```

The use-case is to install non-free packages such as raspi3-firmware.

**Comment by llimeht** [comment]
A comma-separated string of components doesn't seem unreasonable given that is what debootstrap wants but a yaml list is perhaps more in keeping with the data types that are present. 

(Note that the yaml list can't be used until template expansion issues from #13 is sorted out)

**Comment by larswirzenius** [comment]
The template expansion now works with lists, so I'd prefer this patch to be reworked get a YAML list of components to give to qemu-debootstrap.

**Comment by stapelberg** [comment]
Do you just want to go ahead and implement it? Let me know if you’d prefer to retrieve it as a contribution, but I think it’d be quicker if you did it (provided you have the time) :)

**Comment by larswirzenius** [comment]
Done.
