### ISSUE TITLE
question: where should the yaml files for official Debian images live?

### ISSUE THREAD

**Issue by stapelberg** [larswirzenius/vmdb2#21]
I’m looking to eventually publish an official Debian image for the Raspberry Pi 3, and have a yaml file which produces such an image (currently still requiring a bunch of vmdb2 changes, for which issues/pull requests have been filed).

I’m wondering where that yaml file and supporting files should live?

Should they be maintained in the vmdb2 repository so that users can just install vmdb2 and build an image right away? IIUC, this was the model we used in vmdebootstrap.

Or should they be maintained in a separate repository to decouple changes from changes to vmdb2?

**Comment by larswirzenius** [comment]
Having them live in the vmdb2 repository sounds to me like a strange idea. It'd mean changing vmdb2.git and triggering CI builds whenever a Pi image spec change happens. Please put them in a separate repo.

**Comment by llimeht** [comment]
@stapelberg, I like the idea of collating some examples to help others. Ansible has, for instance, an "ansible-examples" repo. I'd be happy to contribute some examples to such an effort too (and it would make sense to have them linked to from the README). 

Some of vmdb2.git's current examples could perhaps migrate there too.

I'm not sure how one deals with bit-rot within the examples repository that will inevitably happen, as Lars points out, due either to changes in the distribution(s) or changes in vmdb2. Of course, vmdb2.git is currently not isolated from Debian in that it explicitly includes mirror and release details in its examples and that information needs to be maintained with time. I think that's a problem that can be worried about later and we've already seen PRs to update mirror details in vmdb2's examples.

**Comment by stapelberg** [comment]
I’m thinking of creating a raspi3-image repository, and possibly including vmdb2 in a known-working version as a git submodule. That way, users can default to (or fallback to, depending on personal preference) the known-working version of vmdb2.

We could then collect this is an example by referencing that repository from the vmdb2 repository.

**Comment by larswirzenius** [comment]
Given that vmdb2 is very much alpha level software, I'm not too worried about bit rot yet. I'm happy to include a few .vmdb files in vmdb.git, for use as examples and test suites.

Later on, when vmdb2 stabilised, I'm happy to make its release process require that a known-good set of vmdb files build correctly. Those files could come from a raspi3-image repository. This way, every release of vmdb2 would work with at least some version of those files.

**Comment by stapelberg** [comment]
> Later on, when vmdb2 stabilised, I'm happy to make its release process require that a known-good set of vmdb files build correctly. Those files could come from a raspi3-image repository. This way, every release of vmdb2 would work with at least some version of those files.

Sounds good to me, thanks.
