### ISSUE TITLE
What’s the difference between .vmdb, .yaml and .yml files?

### ISSUE THREAD

**Issue by stapelberg** [larswirzenius/vmdb2#7]
All seem to contain YAML. Do they have different roles? It’s not clear to me from the documentation.

**Comment by llimeht** [comment]
ansible-playbook(1) refers to .yml files and that seems worthwhile preserving.

As for vmdb2's own files, picking one of .vmdb or .yaml is probably appropriate at this time. I am not aware of any distinction between them.

**Comment by larswirzenius** [comment]
.vmdb is an input file for vmdb. The source tree has simple.yaml, from before I had settled on .vmdb. I'll fix that.

.yml is customarily used with Ansible.

**Comment by larswirzenius** [comment]
Fixed in the code now.
